name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or any version your project requires
        distribution: 'temurin' # Specify the Java distribution, e.g., 'temurin'

    - name: Cache SonarScanner
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/sonar-project.properties') }}

    - name: Install SonarScanner
      run: |
          curl -sSfL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.8.0.2856-linux.zip -o sonar-scanner.zip
          unzip sonar-scanner.zip -d $HOME/
          echo "$HOME/sonar-scanner-4.8.0.2856-linux/bin" >> $GITHUB_PATH
      
    - name: Run SonarQube Scan
      run: |
        sonar-scanner -Dsonar.projectKey=socail-media \
                      -Dsonar.host.url= {{ secrets.SONAR_URL }}  \
                      -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                      -Dsonar.sources=.
