name: SonarQube Analysis

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonarQubeAnalysis:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Run static analysis with SonarQube
      - name: Run SonarQube Scanner
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          curl -o sonar-scanner.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-5.1.2.36732-linux.zip
          unzip sonar-scanner.zip
          mv sonar-scanner-5.1.2.36732-linux sonar-scanner
          ./sonar-scanner/bin/sonar-scanner \
            -Dsonar.projectKey=TurboShipping \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://1bd040b7-c6b4-4122-bee7-730d7d2b3d3f-10-244-3-70-30677.spch.r.killercoda.com \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}
