name: SonarQube Scan

on:
  push:
    branches:
      - main

jobs:
  sonar-scanner:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: '11' # or any version your project requires

    - name: Cache SonarScanner
      uses: actions/cache@v2
      with:
        path: ~/.sonar/cache
        key: ${{ runner.os }}-sonar-cache-${{ hashFiles('**/sonar-project.properties') }}

    - name: Install SonarScanner
      run: |
        curl -sSfL https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/4.7.0.2740/sonar-scanner-cli-4.7.0.2740-linux.zip -o sonar-scanner.zip
        unzip sonar-scanner.zip -d $HOME/
        echo "$HOME/sonar-scanner-4.7.0.2740-linux/bin" >> $GITHUB_PATH

    - name: Run SonarQube Scan
      run: |
        sonar-scanner -Dsonar.projectKey=TurboShipping \
                      -Dsonar.host.url=https://1bd040b7-c6b4-4122-bee7-730d7d2b3d3f-10-244-3-70-30677.spch.r.killercoda.com  \
                      -Dsonar.login=${{ secrets.SONAR_TOKEN }} \
                      -Dsonar.sources=.
